// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: network/services/kad_rpc.proto

package services

import (
	api "github.com/danmuck/dps_net/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ////
// Request/Response Messages
// //
type PING struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PING) Reset() {
	*x = PING{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PING) ProtoMessage() {}

func (x *PING) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PING.ProtoReflect.Descriptor instead.
func (*PING) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *PING) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PING) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ACK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACK) Reset() {
	*x = ACK{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACK) ProtoMessage() {}

func (x *ACK) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACK.ProtoReflect.Descriptor instead.
func (*ACK) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ACK) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ACK) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type STORE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *STORE) Reset() {
	*x = STORE{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STORE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STORE) ProtoMessage() {}

func (x *STORE) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STORE.ProtoReflect.Descriptor instead.
func (*STORE) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *STORE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *STORE) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *STORE) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DELETE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DELETE) Reset() {
	*x = DELETE{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DELETE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DELETE) ProtoMessage() {}

func (x *DELETE) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DELETE.ProtoReflect.Descriptor instead.
func (*DELETE) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *DELETE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DELETE) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type FIND_NODE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	TargetId      []byte                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FIND_NODE) Reset() {
	*x = FIND_NODE{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FIND_NODE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIND_NODE) ProtoMessage() {}

func (x *FIND_NODE) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIND_NODE.ProtoReflect.Descriptor instead.
func (*FIND_NODE) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *FIND_NODE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *FIND_NODE) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

type FIND_VALUE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FIND_VALUE) Reset() {
	*x = FIND_VALUE{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FIND_VALUE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIND_VALUE) ProtoMessage() {}

func (x *FIND_VALUE) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIND_VALUE.ProtoReflect.Descriptor instead.
func (*FIND_VALUE) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *FIND_VALUE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *FIND_VALUE) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type NODES struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Nodes         []*api.Contact         `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NODES) Reset() {
	*x = NODES{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NODES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NODES) ProtoMessage() {}

func (x *NODES) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NODES.ProtoReflect.Descriptor instead.
func (*NODES) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *NODES) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *NODES) GetNodes() []*api.Contact {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type VALUE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Nodes         []*api.Contact         `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VALUE) Reset() {
	*x = VALUE{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VALUE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VALUE) ProtoMessage() {}

func (x *VALUE) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VALUE.ProtoReflect.Descriptor instead.
func (*VALUE) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *VALUE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *VALUE) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *VALUE) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *VALUE) GetNodes() []*api.Contact {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type REFRESH struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *REFRESH) Reset() {
	*x = REFRESH{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *REFRESH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*REFRESH) ProtoMessage() {}

func (x *REFRESH) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use REFRESH.ProtoReflect.Descriptor instead.
func (*REFRESH) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *REFRESH) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *REFRESH) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// ////
// Top-level RPC
// //
type Kademlia_RPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Kademlia_RPC_Ping
	//	*Kademlia_RPC_Ack
	//	*Kademlia_RPC_Store
	//	*Kademlia_RPC_Delete
	//	*Kademlia_RPC_FindNode
	//	*Kademlia_RPC_FindValue
	//	*Kademlia_RPC_Nodes
	//	*Kademlia_RPC_Value
	//	*Kademlia_RPC_Refresh
	Payload       isKademlia_RPC_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kademlia_RPC) Reset() {
	*x = Kademlia_RPC{}
	mi := &file_network_services_kad_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kademlia_RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kademlia_RPC) ProtoMessage() {}

func (x *Kademlia_RPC) ProtoReflect() protoreflect.Message {
	mi := &file_network_services_kad_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kademlia_RPC.ProtoReflect.Descriptor instead.
func (*Kademlia_RPC) Descriptor() ([]byte, []int) {
	return file_network_services_kad_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *Kademlia_RPC) GetPayload() isKademlia_RPC_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Kademlia_RPC) GetPing() *PING {
	if x != nil {
		if x, ok := x.Payload.(*Kademlia_RPC_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Kademlia_RPC) GetAck() *ACK {
	if x != nil {
		if x, ok := x.Payload.(*Kademlia_RPC_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Kademlia_RPC) GetStore() *STORE {
	if x != nil {
		if x, ok := x.Payload.(*Kademlia_RPC_Store); ok {
			return x.Store
		}
	}
	return nil
}

func (x *Kademlia_RPC) GetDelete() *DELETE {
	if x != nil {
		if x, ok := x.Payload.(*Kademlia_RPC_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Kademlia_RPC) GetFindNode() *FIND_NODE {
	if x != nil {
		if x, ok := x.Payload.(*Kademlia_RPC_FindNode); ok {
			return x.FindNode
		}
	}
	return nil
}

func (x *Kademlia_RPC) GetFindValue() *FIND_VALUE {
	if x != nil {
		if x, ok := x.Payload.(*Kademlia_RPC_FindValue); ok {
			return x.FindValue
		}
	}
	return nil
}

func (x *Kademlia_RPC) GetNodes() *NODES {
	if x != nil {
		if x, ok := x.Payload.(*Kademlia_RPC_Nodes); ok {
			return x.Nodes
		}
	}
	return nil
}

func (x *Kademlia_RPC) GetValue() *VALUE {
	if x != nil {
		if x, ok := x.Payload.(*Kademlia_RPC_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Kademlia_RPC) GetRefresh() *REFRESH {
	if x != nil {
		if x, ok := x.Payload.(*Kademlia_RPC_Refresh); ok {
			return x.Refresh
		}
	}
	return nil
}

type isKademlia_RPC_Payload interface {
	isKademlia_RPC_Payload()
}

type Kademlia_RPC_Ping struct {
	Ping *PING `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type Kademlia_RPC_Ack struct {
	Ack *ACK `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type Kademlia_RPC_Store struct {
	Store *STORE `protobuf:"bytes,3,opt,name=store,proto3,oneof"`
}

type Kademlia_RPC_Delete struct {
	Delete *DELETE `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

type Kademlia_RPC_FindNode struct {
	FindNode *FIND_NODE `protobuf:"bytes,5,opt,name=find_node,json=findNode,proto3,oneof"`
}

type Kademlia_RPC_FindValue struct {
	FindValue *FIND_VALUE `protobuf:"bytes,6,opt,name=find_value,json=findValue,proto3,oneof"`
}

type Kademlia_RPC_Nodes struct {
	Nodes *NODES `protobuf:"bytes,7,opt,name=nodes,proto3,oneof"`
}

type Kademlia_RPC_Value struct {
	Value *VALUE `protobuf:"bytes,8,opt,name=value,proto3,oneof"`
}

type Kademlia_RPC_Refresh struct {
	Refresh *REFRESH `protobuf:"bytes,9,opt,name=refresh,proto3,oneof"`
}

func (*Kademlia_RPC_Ping) isKademlia_RPC_Payload() {}

func (*Kademlia_RPC_Ack) isKademlia_RPC_Payload() {}

func (*Kademlia_RPC_Store) isKademlia_RPC_Payload() {}

func (*Kademlia_RPC_Delete) isKademlia_RPC_Payload() {}

func (*Kademlia_RPC_FindNode) isKademlia_RPC_Payload() {}

func (*Kademlia_RPC_FindValue) isKademlia_RPC_Payload() {}

func (*Kademlia_RPC_Nodes) isKademlia_RPC_Payload() {}

func (*Kademlia_RPC_Value) isKademlia_RPC_Payload() {}

func (*Kademlia_RPC_Refresh) isKademlia_RPC_Payload() {}

var File_network_services_kad_rpc_proto protoreflect.FileDescriptor

const file_network_services_kad_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1enetwork/services/kad_rpc.proto\x12\bservices\x1a\rapi/rpc.proto\">\n" +
	"\x04PING\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"=\n" +
	"\x03ACK\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"Q\n" +
	"\x05STORE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"<\n" +
	"\x06DELETE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"J\n" +
	"\tFIND_NODE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\fR\btargetId\"@\n" +
	"\n" +
	"FIND_VALUE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"M\n" +
	"\x05NODES\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\"\n" +
	"\x05nodes\x18\x02 \x03(\v2\f.api.ContactR\x05nodes\"u\n" +
	"\x05VALUE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\"\n" +
	"\x05nodes\x18\x04 \x03(\v2\f.api.ContactR\x05nodes\"=\n" +
	"\aREFRESH\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\xa3\x03\n" +
	"\fKademlia_RPC\x12$\n" +
	"\x04ping\x18\x01 \x01(\v2\x0e.services.PINGH\x00R\x04ping\x12!\n" +
	"\x03ack\x18\x02 \x01(\v2\r.services.ACKH\x00R\x03ack\x12'\n" +
	"\x05store\x18\x03 \x01(\v2\x0f.services.STOREH\x00R\x05store\x12*\n" +
	"\x06delete\x18\x04 \x01(\v2\x10.services.DELETEH\x00R\x06delete\x122\n" +
	"\tfind_node\x18\x05 \x01(\v2\x13.services.FIND_NODEH\x00R\bfindNode\x125\n" +
	"\n" +
	"find_value\x18\x06 \x01(\v2\x14.services.FIND_VALUEH\x00R\tfindValue\x12'\n" +
	"\x05nodes\x18\a \x01(\v2\x0f.services.NODESH\x00R\x05nodes\x12'\n" +
	"\x05value\x18\b \x01(\v2\x0f.services.VALUEH\x00R\x05value\x12-\n" +
	"\arefresh\x18\t \x01(\v2\x11.services.REFRESHH\x00R\arefreshB\t\n" +
	"\apayloadB-Z+github.com/danmuck/dps_net/network/servicesb\x06proto3"

var (
	file_network_services_kad_rpc_proto_rawDescOnce sync.Once
	file_network_services_kad_rpc_proto_rawDescData []byte
)

func file_network_services_kad_rpc_proto_rawDescGZIP() []byte {
	file_network_services_kad_rpc_proto_rawDescOnce.Do(func() {
		file_network_services_kad_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_services_kad_rpc_proto_rawDesc), len(file_network_services_kad_rpc_proto_rawDesc)))
	})
	return file_network_services_kad_rpc_proto_rawDescData
}

var file_network_services_kad_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_network_services_kad_rpc_proto_goTypes = []any{
	(*PING)(nil),         // 0: services.PING
	(*ACK)(nil),          // 1: services.ACK
	(*STORE)(nil),        // 2: services.STORE
	(*DELETE)(nil),       // 3: services.DELETE
	(*FIND_NODE)(nil),    // 4: services.FIND_NODE
	(*FIND_VALUE)(nil),   // 5: services.FIND_VALUE
	(*NODES)(nil),        // 6: services.NODES
	(*VALUE)(nil),        // 7: services.VALUE
	(*REFRESH)(nil),      // 8: services.REFRESH
	(*Kademlia_RPC)(nil), // 9: services.Kademlia_RPC
	(*api.Contact)(nil),  // 10: api.Contact
}
var file_network_services_kad_rpc_proto_depIdxs = []int32{
	10, // 0: services.PING.from:type_name -> api.Contact
	10, // 1: services.ACK.from:type_name -> api.Contact
	10, // 2: services.STORE.from:type_name -> api.Contact
	10, // 3: services.DELETE.from:type_name -> api.Contact
	10, // 4: services.FIND_NODE.from:type_name -> api.Contact
	10, // 5: services.FIND_VALUE.from:type_name -> api.Contact
	10, // 6: services.NODES.from:type_name -> api.Contact
	10, // 7: services.NODES.nodes:type_name -> api.Contact
	10, // 8: services.VALUE.from:type_name -> api.Contact
	10, // 9: services.VALUE.nodes:type_name -> api.Contact
	10, // 10: services.REFRESH.from:type_name -> api.Contact
	0,  // 11: services.Kademlia_RPC.ping:type_name -> services.PING
	1,  // 12: services.Kademlia_RPC.ack:type_name -> services.ACK
	2,  // 13: services.Kademlia_RPC.store:type_name -> services.STORE
	3,  // 14: services.Kademlia_RPC.delete:type_name -> services.DELETE
	4,  // 15: services.Kademlia_RPC.find_node:type_name -> services.FIND_NODE
	5,  // 16: services.Kademlia_RPC.find_value:type_name -> services.FIND_VALUE
	6,  // 17: services.Kademlia_RPC.nodes:type_name -> services.NODES
	7,  // 18: services.Kademlia_RPC.value:type_name -> services.VALUE
	8,  // 19: services.Kademlia_RPC.refresh:type_name -> services.REFRESH
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_network_services_kad_rpc_proto_init() }
func file_network_services_kad_rpc_proto_init() {
	if File_network_services_kad_rpc_proto != nil {
		return
	}
	file_network_services_kad_rpc_proto_msgTypes[9].OneofWrappers = []any{
		(*Kademlia_RPC_Ping)(nil),
		(*Kademlia_RPC_Ack)(nil),
		(*Kademlia_RPC_Store)(nil),
		(*Kademlia_RPC_Delete)(nil),
		(*Kademlia_RPC_FindNode)(nil),
		(*Kademlia_RPC_FindValue)(nil),
		(*Kademlia_RPC_Nodes)(nil),
		(*Kademlia_RPC_Value)(nil),
		(*Kademlia_RPC_Refresh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_services_kad_rpc_proto_rawDesc), len(file_network_services_kad_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_services_kad_rpc_proto_goTypes,
		DependencyIndexes: file_network_services_kad_rpc_proto_depIdxs,
		MessageInfos:      file_network_services_kad_rpc_proto_msgTypes,
	}.Build()
	File_network_services_kad_rpc_proto = out.File
	file_network_services_kad_rpc_proto_goTypes = nil
	file_network_services_kad_rpc_proto_depIdxs = nil
}
