// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: network/services/kademlia.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KademliaService_Ping_FullMethodName      = "/services.KademliaService/Ping"
	KademliaService_Store_FullMethodName     = "/services.KademliaService/Store"
	KademliaService_Delete_FullMethodName    = "/services.KademliaService/Delete"
	KademliaService_FindNode_FullMethodName  = "/services.KademliaService/FindNode"
	KademliaService_FindValue_FullMethodName = "/services.KademliaService/FindValue"
	KademliaService_Refresh_FullMethodName   = "/services.KademliaService/Refresh"
)

// KademliaServiceClient is the client API for KademliaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ----------------------------------------------------------------
// Core Kademlia service
// ----------------------------------------------------------------
type KademliaServiceClient interface {
	// Ping a node — gets an ACK
	Ping(ctx context.Context, in *PING, opts ...grpc.CallOption) (*ACK, error)
	// Store or overwrite a value
	Store(ctx context.Context, in *STORE, opts ...grpc.CallOption) (*ACK, error)
	// Delete a key
	Delete(ctx context.Context, in *DELETE, opts ...grpc.CallOption) (*ACK, error)
	// Find the k closest nodes to a target ID
	FindNode(ctx context.Context, in *FIND_NODE, opts ...grpc.CallOption) (*NODES, error)
	// Try to fetch a value, or fallback to NODES
	FindValue(ctx context.Context, in *FIND_VALUE, opts ...grpc.CallOption) (*VALUE, error)
	// Refresh a value’s timeout (optional)
	Refresh(ctx context.Context, in *REFRESH, opts ...grpc.CallOption) (*ACK, error)
}

type kademliaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKademliaServiceClient(cc grpc.ClientConnInterface) KademliaServiceClient {
	return &kademliaServiceClient{cc}
}

func (c *kademliaServiceClient) Ping(ctx context.Context, in *PING, opts ...grpc.CallOption) (*ACK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACK)
	err := c.cc.Invoke(ctx, KademliaService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaServiceClient) Store(ctx context.Context, in *STORE, opts ...grpc.CallOption) (*ACK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACK)
	err := c.cc.Invoke(ctx, KademliaService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaServiceClient) Delete(ctx context.Context, in *DELETE, opts ...grpc.CallOption) (*ACK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACK)
	err := c.cc.Invoke(ctx, KademliaService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaServiceClient) FindNode(ctx context.Context, in *FIND_NODE, opts ...grpc.CallOption) (*NODES, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NODES)
	err := c.cc.Invoke(ctx, KademliaService_FindNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaServiceClient) FindValue(ctx context.Context, in *FIND_VALUE, opts ...grpc.CallOption) (*VALUE, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VALUE)
	err := c.cc.Invoke(ctx, KademliaService_FindValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaServiceClient) Refresh(ctx context.Context, in *REFRESH, opts ...grpc.CallOption) (*ACK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACK)
	err := c.cc.Invoke(ctx, KademliaService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KademliaServiceServer is the server API for KademliaService service.
// All implementations must embed UnimplementedKademliaServiceServer
// for forward compatibility.
//
// ----------------------------------------------------------------
// Core Kademlia service
// ----------------------------------------------------------------
type KademliaServiceServer interface {
	// Ping a node — gets an ACK
	Ping(context.Context, *PING) (*ACK, error)
	// Store or overwrite a value
	Store(context.Context, *STORE) (*ACK, error)
	// Delete a key
	Delete(context.Context, *DELETE) (*ACK, error)
	// Find the k closest nodes to a target ID
	FindNode(context.Context, *FIND_NODE) (*NODES, error)
	// Try to fetch a value, or fallback to NODES
	FindValue(context.Context, *FIND_VALUE) (*VALUE, error)
	// Refresh a value’s timeout (optional)
	Refresh(context.Context, *REFRESH) (*ACK, error)
	mustEmbedUnimplementedKademliaServiceServer()
}

// UnimplementedKademliaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKademliaServiceServer struct{}

func (UnimplementedKademliaServiceServer) Ping(context.Context, *PING) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedKademliaServiceServer) Store(context.Context, *STORE) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedKademliaServiceServer) Delete(context.Context, *DELETE) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKademliaServiceServer) FindNode(context.Context, *FIND_NODE) (*NODES, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindNode not implemented")
}
func (UnimplementedKademliaServiceServer) FindValue(context.Context, *FIND_VALUE) (*VALUE, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindValue not implemented")
}
func (UnimplementedKademliaServiceServer) Refresh(context.Context, *REFRESH) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedKademliaServiceServer) mustEmbedUnimplementedKademliaServiceServer() {}
func (UnimplementedKademliaServiceServer) testEmbeddedByValue()                         {}

// UnsafeKademliaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KademliaServiceServer will
// result in compilation errors.
type UnsafeKademliaServiceServer interface {
	mustEmbedUnimplementedKademliaServiceServer()
}

func RegisterKademliaServiceServer(s grpc.ServiceRegistrar, srv KademliaServiceServer) {
	// If the following call pancis, it indicates UnimplementedKademliaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KademliaService_ServiceDesc, srv)
}

func _KademliaService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PING)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KademliaService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServiceServer).Ping(ctx, req.(*PING))
	}
	return interceptor(ctx, in, info, handler)
}

func _KademliaService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(STORE)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KademliaService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServiceServer).Store(ctx, req.(*STORE))
	}
	return interceptor(ctx, in, info, handler)
}

func _KademliaService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DELETE)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KademliaService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServiceServer).Delete(ctx, req.(*DELETE))
	}
	return interceptor(ctx, in, info, handler)
}

func _KademliaService_FindNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FIND_NODE)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServiceServer).FindNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KademliaService_FindNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServiceServer).FindNode(ctx, req.(*FIND_NODE))
	}
	return interceptor(ctx, in, info, handler)
}

func _KademliaService_FindValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FIND_VALUE)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServiceServer).FindValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KademliaService_FindValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServiceServer).FindValue(ctx, req.(*FIND_VALUE))
	}
	return interceptor(ctx, in, info, handler)
}

func _KademliaService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(REFRESH)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KademliaService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServiceServer).Refresh(ctx, req.(*REFRESH))
	}
	return interceptor(ctx, in, info, handler)
}

// KademliaService_ServiceDesc is the grpc.ServiceDesc for KademliaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KademliaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.KademliaService",
	HandlerType: (*KademliaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _KademliaService_Ping_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _KademliaService_Store_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KademliaService_Delete_Handler,
		},
		{
			MethodName: "FindNode",
			Handler:    _KademliaService_FindNode_Handler,
		},
		{
			MethodName: "FindValue",
			Handler:    _KademliaService_FindValue_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _KademliaService_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/services/kademlia.proto",
}
