// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: network/routing/kademlia.proto

package routing

import (
	api "github.com/danmuck/dps_net/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------------------------------------------
// Messages
// ----------------------------------------------------------------
type PING struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PING) Reset() {
	*x = PING{}
	mi := &file_network_routing_kademlia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PING) ProtoMessage() {}

func (x *PING) ProtoReflect() protoreflect.Message {
	mi := &file_network_routing_kademlia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PING.ProtoReflect.Descriptor instead.
func (*PING) Descriptor() ([]byte, []int) {
	return file_network_routing_kademlia_proto_rawDescGZIP(), []int{0}
}

func (x *PING) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PING) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ACK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACK) Reset() {
	*x = ACK{}
	mi := &file_network_routing_kademlia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACK) ProtoMessage() {}

func (x *ACK) ProtoReflect() protoreflect.Message {
	mi := &file_network_routing_kademlia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACK.ProtoReflect.Descriptor instead.
func (*ACK) Descriptor() ([]byte, []int) {
	return file_network_routing_kademlia_proto_rawDescGZIP(), []int{1}
}

func (x *ACK) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ACK) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type STORE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *STORE) Reset() {
	*x = STORE{}
	mi := &file_network_routing_kademlia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STORE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STORE) ProtoMessage() {}

func (x *STORE) ProtoReflect() protoreflect.Message {
	mi := &file_network_routing_kademlia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STORE.ProtoReflect.Descriptor instead.
func (*STORE) Descriptor() ([]byte, []int) {
	return file_network_routing_kademlia_proto_rawDescGZIP(), []int{2}
}

func (x *STORE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *STORE) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *STORE) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DELETE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DELETE) Reset() {
	*x = DELETE{}
	mi := &file_network_routing_kademlia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DELETE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DELETE) ProtoMessage() {}

func (x *DELETE) ProtoReflect() protoreflect.Message {
	mi := &file_network_routing_kademlia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DELETE.ProtoReflect.Descriptor instead.
func (*DELETE) Descriptor() ([]byte, []int) {
	return file_network_routing_kademlia_proto_rawDescGZIP(), []int{3}
}

func (x *DELETE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DELETE) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type FIND_NODE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	TargetId      []byte                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FIND_NODE) Reset() {
	*x = FIND_NODE{}
	mi := &file_network_routing_kademlia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FIND_NODE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIND_NODE) ProtoMessage() {}

func (x *FIND_NODE) ProtoReflect() protoreflect.Message {
	mi := &file_network_routing_kademlia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIND_NODE.ProtoReflect.Descriptor instead.
func (*FIND_NODE) Descriptor() ([]byte, []int) {
	return file_network_routing_kademlia_proto_rawDescGZIP(), []int{4}
}

func (x *FIND_NODE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *FIND_NODE) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

type FIND_VALUE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FIND_VALUE) Reset() {
	*x = FIND_VALUE{}
	mi := &file_network_routing_kademlia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FIND_VALUE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIND_VALUE) ProtoMessage() {}

func (x *FIND_VALUE) ProtoReflect() protoreflect.Message {
	mi := &file_network_routing_kademlia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIND_VALUE.ProtoReflect.Descriptor instead.
func (*FIND_VALUE) Descriptor() ([]byte, []int) {
	return file_network_routing_kademlia_proto_rawDescGZIP(), []int{5}
}

func (x *FIND_VALUE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *FIND_VALUE) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type NODES struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Nodes         []*api.Contact         `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NODES) Reset() {
	*x = NODES{}
	mi := &file_network_routing_kademlia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NODES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NODES) ProtoMessage() {}

func (x *NODES) ProtoReflect() protoreflect.Message {
	mi := &file_network_routing_kademlia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NODES.ProtoReflect.Descriptor instead.
func (*NODES) Descriptor() ([]byte, []int) {
	return file_network_routing_kademlia_proto_rawDescGZIP(), []int{6}
}

func (x *NODES) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *NODES) GetNodes() []*api.Contact {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type VALUE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Nodes         []*api.Contact         `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VALUE) Reset() {
	*x = VALUE{}
	mi := &file_network_routing_kademlia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VALUE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VALUE) ProtoMessage() {}

func (x *VALUE) ProtoReflect() protoreflect.Message {
	mi := &file_network_routing_kademlia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VALUE.ProtoReflect.Descriptor instead.
func (*VALUE) Descriptor() ([]byte, []int) {
	return file_network_routing_kademlia_proto_rawDescGZIP(), []int{7}
}

func (x *VALUE) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *VALUE) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *VALUE) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *VALUE) GetNodes() []*api.Contact {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type REFRESH struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *api.Contact           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *REFRESH) Reset() {
	*x = REFRESH{}
	mi := &file_network_routing_kademlia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *REFRESH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*REFRESH) ProtoMessage() {}

func (x *REFRESH) ProtoReflect() protoreflect.Message {
	mi := &file_network_routing_kademlia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use REFRESH.ProtoReflect.Descriptor instead.
func (*REFRESH) Descriptor() ([]byte, []int) {
	return file_network_routing_kademlia_proto_rawDescGZIP(), []int{8}
}

func (x *REFRESH) GetFrom() *api.Contact {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *REFRESH) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_network_routing_kademlia_proto protoreflect.FileDescriptor

const file_network_routing_kademlia_proto_rawDesc = "" +
	"\n" +
	"\x1enetwork/routing/kademlia.proto\x12\arouting\x1a\rapi/rpc.proto\">\n" +
	"\x04PING\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"=\n" +
	"\x03ACK\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"Q\n" +
	"\x05STORE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"<\n" +
	"\x06DELETE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"J\n" +
	"\tFIND_NODE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\fR\btargetId\"@\n" +
	"\n" +
	"FIND_VALUE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"M\n" +
	"\x05NODES\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\"\n" +
	"\x05nodes\x18\x02 \x03(\v2\f.api.ContactR\x05nodes\"u\n" +
	"\x05VALUE\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\"\n" +
	"\x05nodes\x18\x04 \x03(\v2\f.api.ContactR\x05nodes\"=\n" +
	"\aREFRESH\x12 \n" +
	"\x04from\x18\x01 \x01(\v2\f.api.ContactR\x04from\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key2\x93\x02\n" +
	"\x0fKademliaService\x12#\n" +
	"\x04Ping\x12\r.routing.PING\x1a\f.routing.ACK\x12%\n" +
	"\x05Store\x12\x0e.routing.STORE\x1a\f.routing.ACK\x12'\n" +
	"\x06Delete\x12\x0f.routing.DELETE\x1a\f.routing.ACK\x12.\n" +
	"\bFindNode\x12\x12.routing.FIND_NODE\x1a\x0e.routing.NODES\x120\n" +
	"\tFindValue\x12\x13.routing.FIND_VALUE\x1a\x0e.routing.VALUE\x12)\n" +
	"\aRefresh\x12\x10.routing.REFRESH\x1a\f.routing.ACKB,Z*github.com/danmuck/dps_net/network/routingb\x06proto3"

var (
	file_network_routing_kademlia_proto_rawDescOnce sync.Once
	file_network_routing_kademlia_proto_rawDescData []byte
)

func file_network_routing_kademlia_proto_rawDescGZIP() []byte {
	file_network_routing_kademlia_proto_rawDescOnce.Do(func() {
		file_network_routing_kademlia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_routing_kademlia_proto_rawDesc), len(file_network_routing_kademlia_proto_rawDesc)))
	})
	return file_network_routing_kademlia_proto_rawDescData
}

var file_network_routing_kademlia_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_network_routing_kademlia_proto_goTypes = []any{
	(*PING)(nil),        // 0: routing.PING
	(*ACK)(nil),         // 1: routing.ACK
	(*STORE)(nil),       // 2: routing.STORE
	(*DELETE)(nil),      // 3: routing.DELETE
	(*FIND_NODE)(nil),   // 4: routing.FIND_NODE
	(*FIND_VALUE)(nil),  // 5: routing.FIND_VALUE
	(*NODES)(nil),       // 6: routing.NODES
	(*VALUE)(nil),       // 7: routing.VALUE
	(*REFRESH)(nil),     // 8: routing.REFRESH
	(*api.Contact)(nil), // 9: api.Contact
}
var file_network_routing_kademlia_proto_depIdxs = []int32{
	9,  // 0: routing.PING.from:type_name -> api.Contact
	9,  // 1: routing.ACK.from:type_name -> api.Contact
	9,  // 2: routing.STORE.from:type_name -> api.Contact
	9,  // 3: routing.DELETE.from:type_name -> api.Contact
	9,  // 4: routing.FIND_NODE.from:type_name -> api.Contact
	9,  // 5: routing.FIND_VALUE.from:type_name -> api.Contact
	9,  // 6: routing.NODES.from:type_name -> api.Contact
	9,  // 7: routing.NODES.nodes:type_name -> api.Contact
	9,  // 8: routing.VALUE.from:type_name -> api.Contact
	9,  // 9: routing.VALUE.nodes:type_name -> api.Contact
	9,  // 10: routing.REFRESH.from:type_name -> api.Contact
	0,  // 11: routing.KademliaService.Ping:input_type -> routing.PING
	2,  // 12: routing.KademliaService.Store:input_type -> routing.STORE
	3,  // 13: routing.KademliaService.Delete:input_type -> routing.DELETE
	4,  // 14: routing.KademliaService.FindNode:input_type -> routing.FIND_NODE
	5,  // 15: routing.KademliaService.FindValue:input_type -> routing.FIND_VALUE
	8,  // 16: routing.KademliaService.Refresh:input_type -> routing.REFRESH
	1,  // 17: routing.KademliaService.Ping:output_type -> routing.ACK
	1,  // 18: routing.KademliaService.Store:output_type -> routing.ACK
	1,  // 19: routing.KademliaService.Delete:output_type -> routing.ACK
	6,  // 20: routing.KademliaService.FindNode:output_type -> routing.NODES
	7,  // 21: routing.KademliaService.FindValue:output_type -> routing.VALUE
	1,  // 22: routing.KademliaService.Refresh:output_type -> routing.ACK
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_network_routing_kademlia_proto_init() }
func file_network_routing_kademlia_proto_init() {
	if File_network_routing_kademlia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_routing_kademlia_proto_rawDesc), len(file_network_routing_kademlia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_routing_kademlia_proto_goTypes,
		DependencyIndexes: file_network_routing_kademlia_proto_depIdxs,
		MessageInfos:      file_network_routing_kademlia_proto_msgTypes,
	}.Build()
	File_network_routing_kademlia_proto = out.File
	file_network_routing_kademlia_proto_goTypes = nil
	file_network_routing_kademlia_proto_depIdxs = nil
}
