// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/services/router/router.proto

package router

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutingService_Ping_FullMethodName      = "/router.RoutingService/Ping"
	RoutingService_Store_FullMethodName     = "/router.RoutingService/Store"
	RoutingService_Delete_FullMethodName    = "/router.RoutingService/Delete"
	RoutingService_FindNode_FullMethodName  = "/router.RoutingService/FindNode"
	RoutingService_FindValue_FullMethodName = "/router.RoutingService/FindValue"
	RoutingService_Refresh_FullMethodName   = "/router.RoutingService/Refresh"
)

// RoutingServiceClient is the client API for RoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ----------------------------------------------------------------
// Core Routing service
// ----------------------------------------------------------------
type RoutingServiceClient interface {
	// Ping a node — gets an ACK
	Ping(ctx context.Context, in *PING, opts ...grpc.CallOption) (*ACK, error)
	// Store or overwrite a value
	Store(ctx context.Context, in *STORE, opts ...grpc.CallOption) (*ACK, error)
	// Delete a key
	Delete(ctx context.Context, in *DELETE, opts ...grpc.CallOption) (*ACK, error)
	// Find the k closest nodes to a target ID
	FindNode(ctx context.Context, in *FIND_NODE, opts ...grpc.CallOption) (*NODES, error)
	// Try to fetch a value, or fallback to NODES
	FindValue(ctx context.Context, in *FIND_VALUE, opts ...grpc.CallOption) (*VALUE, error)
	// Refresh a value’s timeout (optional)
	Refresh(ctx context.Context, in *REFRESH, opts ...grpc.CallOption) (*ACK, error)
}

type routingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceClient(cc grpc.ClientConnInterface) RoutingServiceClient {
	return &routingServiceClient{cc}
}

func (c *routingServiceClient) Ping(ctx context.Context, in *PING, opts ...grpc.CallOption) (*ACK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACK)
	err := c.cc.Invoke(ctx, RoutingService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) Store(ctx context.Context, in *STORE, opts ...grpc.CallOption) (*ACK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACK)
	err := c.cc.Invoke(ctx, RoutingService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) Delete(ctx context.Context, in *DELETE, opts ...grpc.CallOption) (*ACK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACK)
	err := c.cc.Invoke(ctx, RoutingService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) FindNode(ctx context.Context, in *FIND_NODE, opts ...grpc.CallOption) (*NODES, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NODES)
	err := c.cc.Invoke(ctx, RoutingService_FindNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) FindValue(ctx context.Context, in *FIND_VALUE, opts ...grpc.CallOption) (*VALUE, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VALUE)
	err := c.cc.Invoke(ctx, RoutingService_FindValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) Refresh(ctx context.Context, in *REFRESH, opts ...grpc.CallOption) (*ACK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACK)
	err := c.cc.Invoke(ctx, RoutingService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServiceServer is the server API for RoutingService service.
// All implementations must embed UnimplementedRoutingServiceServer
// for forward compatibility.
//
// ----------------------------------------------------------------
// Core Routing service
// ----------------------------------------------------------------
type RoutingServiceServer interface {
	// Ping a node — gets an ACK
	Ping(context.Context, *PING) (*ACK, error)
	// Store or overwrite a value
	Store(context.Context, *STORE) (*ACK, error)
	// Delete a key
	Delete(context.Context, *DELETE) (*ACK, error)
	// Find the k closest nodes to a target ID
	FindNode(context.Context, *FIND_NODE) (*NODES, error)
	// Try to fetch a value, or fallback to NODES
	FindValue(context.Context, *FIND_VALUE) (*VALUE, error)
	// Refresh a value’s timeout (optional)
	Refresh(context.Context, *REFRESH) (*ACK, error)
	mustEmbedUnimplementedRoutingServiceServer()
}

// UnimplementedRoutingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServiceServer struct{}

func (UnimplementedRoutingServiceServer) Ping(context.Context, *PING) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRoutingServiceServer) Store(context.Context, *STORE) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedRoutingServiceServer) Delete(context.Context, *DELETE) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRoutingServiceServer) FindNode(context.Context, *FIND_NODE) (*NODES, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindNode not implemented")
}
func (UnimplementedRoutingServiceServer) FindValue(context.Context, *FIND_VALUE) (*VALUE, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindValue not implemented")
}
func (UnimplementedRoutingServiceServer) Refresh(context.Context, *REFRESH) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedRoutingServiceServer) mustEmbedUnimplementedRoutingServiceServer() {}
func (UnimplementedRoutingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceServer will
// result in compilation errors.
type UnsafeRoutingServiceServer interface {
	mustEmbedUnimplementedRoutingServiceServer()
}

func RegisterRoutingServiceServer(s grpc.ServiceRegistrar, srv RoutingServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingService_ServiceDesc, srv)
}

func _RoutingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PING)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).Ping(ctx, req.(*PING))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(STORE)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).Store(ctx, req.(*STORE))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DELETE)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).Delete(ctx, req.(*DELETE))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_FindNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FIND_NODE)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).FindNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_FindNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).FindNode(ctx, req.(*FIND_NODE))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_FindValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FIND_VALUE)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).FindValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_FindValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).FindValue(ctx, req.(*FIND_VALUE))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(REFRESH)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).Refresh(ctx, req.(*REFRESH))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutingService_ServiceDesc is the grpc.ServiceDesc for RoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "router.RoutingService",
	HandlerType: (*RoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RoutingService_Ping_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _RoutingService_Store_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RoutingService_Delete_Handler,
		},
		{
			MethodName: "FindNode",
			Handler:    _RoutingService_FindNode_Handler,
		},
		{
			MethodName: "FindValue",
			Handler:    _RoutingService_FindValue_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _RoutingService_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/router/router.proto",
}
