// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/rpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ////
// Contact represents a node in the network.
// //
type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TcpAddress    string                 `protobuf:"bytes,2,opt,name=tcp_address,json=tcpAddress,proto3" json:"tcp_address,omitempty"`
	UdpAddress    string                 `protobuf:"bytes,3,opt,name=udp_address,json=udpAddress,proto3" json:"udp_address,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_api_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_api_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Contact) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Contact) GetTcpAddress() string {
	if x != nil {
		return x.TcpAddress
	}
	return ""
}

func (x *Contact) GetUdpAddress() string {
	if x != nil {
		return x.UdpAddress
	}
	return ""
}

func (x *Contact) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

// ////
// The generic RPC wrapper
// //
type RPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // e.g. "KVService.go".Hash()
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`   // e.g. "GET"
	Sender        *Contact               `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // protobuf‐marshaled request message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC) Reset() {
	*x = RPC{}
	mi := &file_api_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC) ProtoMessage() {}

func (x *RPC) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC.ProtoReflect.Descriptor instead.
func (*RPC) Descriptor() ([]byte, []int) {
	return file_api_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RPC) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RPC) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RPC) GetSender() *Contact {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *RPC) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_api_rpc_proto protoreflect.FileDescriptor

const file_api_rpc_proto_rawDesc = "" +
	"\n" +
	"\rapi/rpc.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x01\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1f\n" +
	"\vtcp_address\x18\x02 \x01(\tR\n" +
	"tcpAddress\x12\x1f\n" +
	"\vudp_address\x18\x03 \x01(\tR\n" +
	"udpAddress\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"w\n" +
	"\x03RPC\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12$\n" +
	"\x06sender\x18\x03 \x01(\v2\f.api.ContactR\x06sender\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload2-\n" +
	"\x0fEndpointHandler\x12\x1a\n" +
	"\x04Call\x12\b.api.RPC\x1a\b.api.RPCB Z\x1egithub.com/danmuck/dps_net/apib\x06proto3"

var (
	file_api_rpc_proto_rawDescOnce sync.Once
	file_api_rpc_proto_rawDescData []byte
)

func file_api_rpc_proto_rawDescGZIP() []byte {
	file_api_rpc_proto_rawDescOnce.Do(func() {
		file_api_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rpc_proto_rawDesc), len(file_api_rpc_proto_rawDesc)))
	})
	return file_api_rpc_proto_rawDescData
}

var file_api_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_rpc_proto_goTypes = []any{
	(*Contact)(nil),               // 0: api.Contact
	(*RPC)(nil),                   // 1: api.RPC
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_rpc_proto_depIdxs = []int32{
	2, // 0: api.Contact.last_seen:type_name -> google.protobuf.Timestamp
	0, // 1: api.RPC.sender:type_name -> api.Contact
	1, // 2: api.EndpointHandler.Call:input_type -> api.RPC
	1, // 3: api.EndpointHandler.Call:output_type -> api.RPC
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_rpc_proto_init() }
func file_api_rpc_proto_init() {
	if File_api_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rpc_proto_rawDesc), len(file_api_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rpc_proto_goTypes,
		DependencyIndexes: file_api_rpc_proto_depIdxs,
		MessageInfos:      file_api_rpc_proto_msgTypes,
	}.Build()
	File_api_rpc_proto = out.File
	file_api_rpc_proto_goTypes = nil
	file_api_rpc_proto_depIdxs = nil
}
